apiVersion: v1
kind: ConfigMap
metadata:
  namespace: stateful
  name: mysql-config
data:
  evolve.sql: |
    drop database if exists evolve;
    create database evolve;
  default_auth: |
    [mysqld]
    default_authentication_plugin= mysql_native_password